### ISSUE TITLE
Certain SIDs cause Winamp lock-ups

### ISSUE THREAD

**Issue by koitsu** [zbych-r/in_sidplay2#1]
Several HVSC 71 SIDs cause this plugin to "faux crash" Winamp, i.e. Winamp becomes completely unresponsive but the SID keeps playing.  One is forced to "End Task" Winamp when this happens or wait for the "Winamp is not responding" dialog.  Happens regardless if songlengths or STIL is enabled.

Some SIDs that exhibit this problem:

```
MUSICIANS\G\Gray_Matt\Driller.sid
MUSICIANS\G\Galway_Martin\Rastan.sid
MUSICIANS\K\KB\Turrican_32k.sid
```

One thing I noticed about the crash: when this happens, the Winamp song length indicator (time remaining / time played) never gets rendered.  Maybe that will help you in tracking down the issue.

**Comment by koitsu** [comment]
Some others I came across.  This was as many as I cared to dig into, but I am sure there are more:

```
MUSICIANS\H\Hubbard_Rob\Auf_Wiedersehen_Monty.sid
MUSICIANS\H\Hubbard_Rob\BMX_Kidz.sid
MUSICIANS\H\Hubbard_Rob\Bump_Set_Spike.sid
MUSICIANS\H\Hubbard_Rob\Chimera.sid
MUSICIANS\H\Hubbard_Rob\Crazy_Comets.sid
MUSICIANS\H\Hubbard_Rob\Delta.sid
MUSICIANS\H\Hubbard_Rob\Dragons_Lair_Part_II.sid
MUSICIANS\H\Hubbard_Rob\Final_Synth_Sample_II.sid
MUSICIANS\H\Hubbard_Rob\Formula_1_Simulator.sid
MUSICIANS\H\Hubbard_Rob\Geoff_Capes_Strongman_Challenge.sid
```

**Comment by devinacker** [comment]
Seems to be an issue with the worker thread and mutex added in 33d99561edc774dfca8ab89d53cb0e87ec47171f. 

`getfileinfo` and `AddSubsongsThreadProc` in in_sidplay2.cpp will both attempt to lock the mutex, but  any time the latter calls `SendMessage` with the handle of either the main window or the playlist window, Winamp will call `getfileinfo` again from the main thread even though the mutex is still being held by the worker thread.

**Comment by devinacker** [comment]
I finally got around to testing a fix for this (and a couple of other related issues I was experiencing with Winamp 5) and opened a PR. Hopefully it can fix the issue for you also.
